// <auto-generated />
namespace _1291163_MVC_EF_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class InitialHotelBooking : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialHotelBooking));
        
        string IMigrationMetadata.Id
        {
            get { return "202601122109161_InitialHotelBooking"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
